# Generated by Django 5.2 on 2025-05-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='gorss_revenue',
            new_name='gross_revenue',
        ),
    ]
