# Generated by Django 5.2 on 2025-06-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_review_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='authenticate.streamingservice'),
        ),
    ]
