# Generated by Django 5.2 on 2025-05-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_rename_gorss_revenue_movie_gross_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
    ]
